### ISSUE TITLE
Implement tagging service

### ISSUE THREAD

**Issue by hlysig** [rudatalab/python-objectcube#14]
The tagging service should be implemented with respect to definition in [https://github.com/rudatalab/python-objectcube/issues/13](https://github.com/rudatalab/python-objectcube/issues/13)

**Comment by bjornthorru** [comment]
@hlysig : This is almost 100% done.  There are issues regarding transaction support, which must be resolved. But the code is ready and test coverage is 100%.

**Comment by bjornthorru** [comment]
I will need help with committing, as the branch needs a merge and I've modified many files...

**Comment by bjornthorru** [comment]
Done
